name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy blog.
    steps:
    # check it to your workflow can access it
    # from: https://github.com/actions/checkout
    - name: Checkout Repository master branch
      uses: actions/checkout@master 
      
    # from: https://github.com/actions/setup-node  
    - name: Setup Node.js 14.x 
      uses: actions/setup-node@master
      with:
        node-version: "14.x"
    
    - name: Setup Git Infomation
      run: | 
        git config --global user.name 'lsgxs2019' 
        git config --global user.email 'lsgxs141@126.com'  
 
    - name: Get Latest Commit Message 
      run: |
        git log --pretty=format:"%s from Github Actions at `date +"%Y-%m-%d %H:%M:%S"`" --date=short -n 1  > commit-message.log
        
    - name: Setup Hexo Dependencies
      run: |
        npm install hexo-cli -g
        npm install
        
    - name: Generate public files
      run: |
        hexo clean
        hexo generate 
        
    - name: Deploy To Github Pages 
      env:
        Github_Pages: github.com/lsgxs2019/lsgxs2019.github.io.git
        Github_Token: ${{ HEXO_DEPLOY_SECRET1 }}
      run: |  
        git clone https://${Github_Pages} .github_pages
        cd .github_pages
        git checkout main
        cd ../
        mv .github_pages/.git/ ./public/
        cd ./public/
        git add .
        git commit -F ../commit-message.log
        git push --force --quiet "https://${Github_Token}@${Github_Pages}" main:main


    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Cache node modules
      uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
                    ${{ runner.os }}-node-

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci

    - name: Deploy
      id: deploy
      uses: sma11black/hexo-action@v1.0.3
      with:
        deploy_key: ${{ secrets.hexo_deploy_secret2 }}

    - name: Get the output
      run: |
                echo "${{ steps.deploy.outputs.notify }}"